### PR TITLE
Specify min Python version

### PR DESCRIPTION
**Pull request by jnothman**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jnothman** [comment]
@conda-forge-admin, please rerender

**Comment by jnothman** [comment]
@conda-forge-admin, please rerender

**Review by wdecoster — APPROVED** [review]

**Comment by jnothman** [comment]
Good to merge, @wdecoster?

**Comment by wdecoster** [comment]
I think so @jnothman, although I only faintly remember getting this into conda-forge in the first place, and things like the docker-parts are something that I can't comment on. But if it builds it builds? :-)

**Comment by jnothman** [comment]
I'm not authorised to merge, so maybe you should @wdecoster. Then #9 as well

**Comment by wdecoster** [comment]
Oh, I wasn't aware of that, alright I will merge this one. But it seems in #9 there are still changes necessary according to the automatic checks?

**Pull request merged**
